name: Create Dated File

on:
  repository_dispatch:
    types: [create-dated-file]

jobs:
  create_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dated file
        env:
          FILE_CONTENT: ${{ github.event.client_payload.content }}
        run: |
          echo "Received content: $FILE_CONTENT"
          now=$(date +"%Y-%m-%d-%H-%M-%S")
          mkdir -p contents
          cat <<EOF > "contents/$now.md"
          $FILE_CONTENT
          EOF
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add contents
          git commit -m "Create dated file: $now.md"
          git push
