name: Create Dated File

on:
  repository_dispatch:
    types: [create-dated-file]

jobs:
  create_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dated file with slug
        env:
          FILE_CONTENT: ${{ github.event.client_payload.content }}
          FILE_TITLE: ${{ github.event.client_payload.title }}
        run: |
          slug=$(echo "$FILE_TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g;s/^-+|-+$//g')
          now=$(date +"%Y-%m-%d")
          filename="contents/${now}-${slug}.md"
          echo "$FILE_CONTENT" | base64 --decode > "$filename"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "$filename"
          git commit -m "Create post: $filename"
          git push
